### ISSUE TITLE
Reproduce ETT results

### ISSUE THREAD

**Issue by rribault-fem** [JeremyChou28/MTSCI#2]
Hello,

I'm trying to reproduce ETT dataset results but I'm not sure about input parameters & evaluation metrics.
See below my log file.
I get the following evaluation results which look quite different from the paper :
mae = 4.727, rmse = 7.933, mape = 60.329%, mse = 62.931, r2 = 0.212, CRPS = 0.4957

[ETT_block_ms0.2_seed1.log](https://github.com/user-attachments/files/17256050/ETT_block_ms0.2_seed1.log)

**Comment by JeremyChou28** [comment]
> Hello,
> 
> I'm trying to reproduce ETT dataset results but I'm not sure about input parameters & evaluation metrics. See below my log file. I get the following evaluation results which look quite different from the paper : mae = 4.727, rmse = 7.933, mape = 60.329%, mse = 62.931, r2 = 0.212, CRPS = 0.4957
> 
> [ETT_block_ms0.2_seed1.log](https://github.com/user-attachments/files/17256050/ETT_block_ms0.2_seed1.log)

Looking at your log files, it looks like there is a problem with the overall missing ratio on val and test.
My reproduction log file is as follows:
[ETT_block_ms0.2_seed1.log](https://github.com/user-attachments/files/17260062/ETT_block_ms0.2_seed1.log)

**Comment by rribault-fem** [comment]
My mistake :-)
